"""Update rating

Revision ID: 84935f0384c8
Revises: 7db350d87f4a
Create Date: 2023-04-10 18:17:49.346865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84935f0384c8'
down_revision = '7db350d87f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_ratings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('image_ratings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_ratings', 'updated_at')
    op.drop_column('image_ratings', 'created_at')
    # ### end Alembic commands ###
